### ISSUE TITLE
Feature request: Change file path on filestore because of a rename in physical storage

### ISSUE THREAD

**Issue by nickreserved** [ipfs/go-filestore#50]
I have my complete FOOBAR collection in filestore.
Now I want, in my disk to rename a folder containing 1000000 TB of data.
Just a folder or file rename.

How filestore handle this EFFICIENTLY?

I see, file paths stored in LevelDB databases.
So, it is easy to implement an additional rename operation (I believe).

If we talk about torrents, filestore is the way torrents work.
EVERY torrent client has a "Set data location".
Because data moved often. This is the case.

So, I propose
ipfs filestore mv [-r] old_path new_path
-r includes all children folders and files (implies that old_path is a path to a directory).
No checks for hashes (if someone runs this command implies that he knows what he does).

**Comment by Stebalien** [comment]
This isn't supported.
